### ISSUE TITLE
Not loging in or registering or storing tokens

### ISSUE THREAD

**Issue by shpleef** [rmcdaniel/angular-codeigniter-seed#7]
Hey rmcdaniel nice code man, i got to working almost, i have the database and the tables populated also i am getting json response correct from the rest controllers to angular frontend but it just keep showing error even when the data.success is true....... please point me to the right direction what am i missing thats all......
![capt2ure](https://cloud.githubusercontent.com/assets/16339855/11886770/13dea026-a52e-11e5-82b8-7267d032607f.JPG)

**Comment by rmcdaniel** [comment]
You need to change your php configuration to only show error messages. It is showing notice messages too.

http://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting

**Comment by shpleef** [comment]
Thanks alot rmcdaneil u pointed me in the right direction, i changed the php.ini settings but it dint make much difference but when i changed the codeigniter error logging from all to only error than it worked like a charm. Nice work :dancers:

**Comment by Ranybaug** [comment]
Hey rmcdaniel ,  awesome code .  But whenever I am submitting on Login Form..I am getting an 404 Error in console as : 

/angular-codeigniter-seed-master/angular-codeigniter-seed-master/api/user/login 404 (Not Found)

since it is making proper request to controller user which is residing in api directory . Moreover I have kept application_folder and system_path in api/index.php as :

$system_path = 'api/system/';

$application_folder = 'api/application/';

 Please let me know if I am missing something ....

**Comment by rmcdaniel** [comment]
Have you setup URL rewriting?

https://ellislab.com/codeigniter/user-guide/general/urls.html

**Comment by Ranybaug** [comment]
Thanks Richard McDaniel !  It works . my URL rewriting was incorrect and  apache-rewrite module  was not enabled hence htaccess was not coming into effect . Thanks a lot once again !.....

I have one question  : 

Just as we can use any database from CodeIgniter by changing db-driver , can we or is it possible to have such configuration for frontend JS  frameworks to select JS Framework for web application.

e,g, I will mention in config section as which JS Framework to use from list of Frameworks such Angular, Prototype , React, Ext ...Jquery ...etc...

since I think invocation of event handlers will be same for all Frameworks , only syntax would be differing . Please correct me If I am wrong since I am not expert with JS Framework and its internals .
